name: Python Scraper Application

on:
  schedule:
  - cron: "0 0 */2 * *"  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          ref: updated_flow

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.16'
        
    - name: Create env file
      run: |
        touch .env
        echo sender_email_id='metadataworksbot@outlook.com' >> .env
        echo sender_email_password='Z0f1S29GQ4GKcrk8' >> .env
        echo receiver_email_id='["katiewheatley@nhs.net","adam@metadataworks.co.uk","bharat.sharma4@nhs.net"]' >> .env
        cat .env
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run script
      run: python api_scraper.py 
      
    - name: commit files
      run: |
        git config --local user.email "scraperbot@metadataworks.co.uk"
        git config --local user.name "David-MDW"
        git add -A
        git commit -m "data_updated_through_scheduler" -a

    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: "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"
        branch: updated_flow
